### ISSUE TITLE
网络模型请教

### ISSUE THREAD

**Issue by helonin** [xuquanfu/capsule_change_detection#1]
请问ChangeCapsule模型中 最后的3个输出 OutSubstrct  OutCos  shared_decoder(seg_caps1) 分别代表什么？哪个输出结果表示的是变化的标签，谢谢！

**Comment by xuquanfu** [comment]
你好，你可以看一下paper，Change Capsule Network for Optical Remote Sensing Image Change Detection。https://www.mdpi.com/2072-4292/13/14/2646#cite。
OutSubstrct是向量差相似性度量的结果。OutCos是余弦相似性度量的结果。shared_decoder(seg_caps1)则用于训练的时候，非变化区域的重建，类似于正则，与原生capsule相似。
如代码或论文有用，请引用我们的论文。
